name: Build NewPipeExtractor

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew jar --stacktrace

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: NewPipeExtractor-JAR
          path: |
            **/build/libs/*.jar
            **/build/reports/**
